class_name GameEnums
extends RefCounted

enum Difficulty { EASY, NORMAL, HARD }
enum FactionControl { PLAYER, AI }
enum RelationBand { NEMESIS, HOSTILE, NEUTRAL, FRIENDLY, CLOSE }
enum TreatyType { NONE, CEASEFIRE, NON_AGGRESSION }
enum StrategicPhase { START, STRATEGY, COMBAT, END }
enum RegionScale { SMALL, MEDIUM, LARGE }
enum FacilityType {
	ECONOMY,
	LARGE_ECONOMY,
	RESOURCE,
	LARGE_RESOURCE,
	RESEARCH,
	PRODUCTION,
	LARGE_PRODUCTION,
}

enum UnitSize { LIGHT, STANDARD, HEAVY }
enum UnitRole { ATTACK, DEFENSE, LONG_RANGE, RECON, SUPPORT }
enum EnvironmentType { GROUND, SPACE, MOON }
enum EnvironmentAptitude { PROFICIENT, STANDARD, POOR }
enum WeaponClass { LIGHT, STANDARD, HEAVY, STRATEGIC }
enum DamageAttribute { BALLISTIC, BEAM, MELEE }
enum RangeClass { MELEE, SHORT, MEDIUM, LONG, STRATEGIC }
enum RowType { FRONT, REAR }
enum BattlePolicy { BALANCED, OFFENSIVE, DEFENSIVE, SUPPORT, RETREAT }
enum TerrainEffect { NORMAL, DIFFICULT, COVER, HAZARDOUS, IMPASSABLE }
enum TargetRule {
	FRONT,
	LOW_HP,
	HIGH_HP,
	LOW_ARMOR,
	HIGH_ARMOR,
	HIGH_SPEED,
	SUPPORT,
	RANDOM,
}
enum SupportTargetRule {
	LOW_HP_RATIO,
	HIGH_HP_LOSS,
	LOW_EN_RATIO,
	HIGH_EN_CONSUMPTION,
	FRONT,
	REAR,
	LEADER,
	ROLE,
	SELF_EXCLUDED,
	SELF_INCLUDED,
}
enum TargetPattern {
	SINGLE,
	FRONT_ROW,
	REAR_ROW,
	LEFT_COLUMN,
	CENTER,
	RIGHT_COLUMN,
	ALL_ENEMIES,
	ALL_ALLIES,
}
enum ActionType { ATTACK, REPAIR, EN_TRANSFER, DEFEND }
enum UnitCondition { ACTIVE, REPAIRING, DESTROYED_RECOVERED }

enum IntelState { UNKNOWN, CONFIRMED }
enum EventImportance { MAIN, SUB }
enum EventEffectType {
	FUNDS,
	MATERIALS,
	TECH_CANDIDATE,
	RESEARCH_MODIFIER,
	PILOT_JOIN,
	PILOT_LEAVE,
	PILOT_INJURE,
	UNIT_GAIN,
	UNIT_LOSE,
	RELATION,
	TREATY,
	ENEMY_REINFORCEMENT,
	EVENT_FLAG,
}
